package com.backend.entities;
// Generated Sep 24, 2019 11:35:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="Admin"
)
public class Admin  implements java.io.Serializable {


     private int id;
     private String adminCode;
     private AdminRole adminRoleId;
     private Company companyID;
     private Date createdDate;
     private String firstName;
     private Integer gender;
     private String iNF_Address;
     private String iNF_AddressReg;
     private String iNF_BankAccount;
     private String iNF_BankName;
     private String iNF_Country;
     private Date iNF_DateOfBirth;
     private String iNF_Nation;
     private String iNF_PlaceOfBirth;
     private String iNF_SourceNation;
     private String identityCard;
     private Boolean isActive;
     private Boolean isDeleted;
     private Boolean isManager;
     private String lastName;
     private String name;
     private String password;
     private String phone;
     private String urlAvatar;
     private String username;

    public Admin() {
    }

    public Admin(String adminCode, AdminRole adminRoleId, Company companyID, Date createdDate, String firstName, Integer gender, String iNF_Address, String iNF_AddressReg, String iNF_BankAccount, String iNF_BankName, String iNF_Country, Date iNF_DateOfBirth, String iNF_Nation, String iNF_PlaceOfBirth, String iNF_SourceNation, String identityCard, Boolean isActive, Boolean isDeleted, Boolean isManager, String lastName, String name, String password, String phone, String urlAvatar, String username) {
       this.adminCode = adminCode;
       this.adminRoleId = adminRoleId;
       this.companyID = companyID;
       this.createdDate = createdDate;
       this.firstName = firstName;
       this.gender = gender;
       this.iNF_Address = iNF_Address;
       this.iNF_AddressReg = iNF_AddressReg;
       this.iNF_BankAccount = iNF_BankAccount;
       this.iNF_BankName = iNF_BankName;
       this.iNF_Country = iNF_Country;
       this.iNF_DateOfBirth = iNF_DateOfBirth;
       this.iNF_Nation = iNF_Nation;
       this.iNF_PlaceOfBirth = iNF_PlaceOfBirth;
       this.iNF_SourceNation = iNF_SourceNation;
       this.identityCard = identityCard;
       this.isActive = isActive;
       this.isDeleted = isDeleted;
       this.isManager = isManager;
       this.lastName = lastName;
       this.name = name;
       this.password = password;
       this.phone = phone;
       this.urlAvatar = urlAvatar;
       this.username = username;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", nullable=false, insertable=false, updatable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="admincode")
    public String getAdminCode() {
        return this.adminCode;
    }
    
    public void setAdminCode(String adminCode) {
        this.adminCode = adminCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AdminRoleID")
    public AdminRole getAdminRoleId() {
        return this.adminRoleId;
    }
    
    public void setAdminRoleId(AdminRole adminRoleId) {
        this.adminRoleId = adminRoleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CompanyID", updatable=false)
    public Company getCompanyID() {
        return this.companyID;
    }
    
    public void setCompanyID(Company companyID) {
        this.companyID = companyID;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", insertable=false, updatable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="FirstName")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Gender")
    public Integer getGender() {
        return this.gender;
    }
    
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    
    @Column(name="iNF_Address")
    public String getiNF_Address() {
        return this.iNF_Address;
    }
    
    public void setiNF_Address(String iNF_Address) {
        this.iNF_Address = iNF_Address;
    }

    
    @Column(name="iNF_AddressReg")
    public String getiNF_AddressReg() {
        return this.iNF_AddressReg;
    }
    
    public void setiNF_AddressReg(String iNF_AddressReg) {
        this.iNF_AddressReg = iNF_AddressReg;
    }

    
    @Column(name="iNF_BankAccount")
    public String getiNF_BankAccount() {
        return this.iNF_BankAccount;
    }
    
    public void setiNF_BankAccount(String iNF_BankAccount) {
        this.iNF_BankAccount = iNF_BankAccount;
    }

    
    @Column(name="iNF_BankName")
    public String getiNF_BankName() {
        return this.iNF_BankName;
    }
    
    public void setiNF_BankName(String iNF_BankName) {
        this.iNF_BankName = iNF_BankName;
    }

    
    @Column(name="iNF_Country")
    public String getiNF_Country() {
        return this.iNF_Country;
    }
    
    public void setiNF_Country(String iNF_Country) {
        this.iNF_Country = iNF_Country;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INF_DateOfBirth", insertable=false, updatable=false, length=23)
    public Date getiNF_DateOfBirth() {
        return this.iNF_DateOfBirth;
    }
    
    public void setiNF_DateOfBirth(Date iNF_DateOfBirth) {
        this.iNF_DateOfBirth = iNF_DateOfBirth;
    }

    
    @Column(name="iNF_Nation")
    public String getiNF_Nation() {
        return this.iNF_Nation;
    }
    
    public void setiNF_Nation(String iNF_Nation) {
        this.iNF_Nation = iNF_Nation;
    }

    
    @Column(name="iNF_PlaceOfBirth")
    public String getiNF_PlaceOfBirth() {
        return this.iNF_PlaceOfBirth;
    }
    
    public void setiNF_PlaceOfBirth(String iNF_PlaceOfBirth) {
        this.iNF_PlaceOfBirth = iNF_PlaceOfBirth;
    }

    
    @Column(name="iNF_SourceNation")
    public String getiNF_SourceNation() {
        return this.iNF_SourceNation;
    }
    
    public void setiNF_SourceNation(String iNF_SourceNation) {
        this.iNF_SourceNation = iNF_SourceNation;
    }

    
    @Column(name="IdentityCard")
    public String getIdentityCard() {
        return this.identityCard;
    }
    
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    
    @Column(name="IsActive", insertable=false)
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="isDeleted", insertable=false, updatable=false)
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    
    @Column(name="IsManager")
    public Boolean getIsManager() {
        return this.isManager;
    }
    
    public void setIsManager(Boolean isManager) {
        this.isManager = isManager;
    }

    
    @Column(name="LastName")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Password", updatable=false, length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="UrlAvatar")
    public String getUrlAvatar() {
        return this.urlAvatar;
    }
    
    public void setUrlAvatar(String urlAvatar) {
        this.urlAvatar = urlAvatar;
    }

    
    @Column(name="Username", unique=true, updatable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


