package com.backend.entities;
// Generated Sep 24, 2019 11:35:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminRole generated by hbm2java
 */
@Entity
@Table(name="AdminRole"
)
public class AdminRole  implements java.io.Serializable {


     private int id;
     private String code;
     private Boolean isActive;
     private Boolean isDeleted;
     private Integer level;
     private String moduleIDs;
     private String moduleUrls;
     private String name;

    public AdminRole() {
    }

    public AdminRole(String code, Boolean isActive, Boolean isDeleted, Integer level, String moduleIDs, String moduleUrls, String name) {
       this.code = code;
       this.isActive = isActive;
       this.isDeleted = isDeleted;
       this.level = level;
       this.moduleIDs = moduleIDs;
       this.moduleUrls = moduleUrls;
       this.name = name;
    }
    public AdminRole(int parseInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", nullable=false, insertable=false, updatable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Code")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="isDeleted", insertable=false, updatable=false)
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    
    @Column(name="Level")
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }

    
    @Column(name="moduleIDs")
    public String getModuleIDs() {
        return this.moduleIDs;
    }
    
    public void setModuleIDs(String moduleIDs) {
        this.moduleIDs = moduleIDs;
    }

    
    @Column(name="moduleUrls")
    public String getModuleUrls() {
        return this.moduleUrls;
    }
    
    public void setModuleUrls(String moduleUrls) {
        this.moduleUrls = moduleUrls;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


