package com.backend.entities;
// Generated Sep 24, 2019 11:35:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdminModule generated by hbm2java
 */
@Entity
@Table(name="AdminModule"
)
public class AdminModule  implements java.io.Serializable {


     private int id;
     private String controller;
     private String icon;
     private Boolean isDeleted;
     private Boolean isShow;
     private Integer level;
     private String name;
     private Integer orderNumber;
     private AdminModule parentId;
     private String routeLink;

    public AdminModule() {
    }

    public AdminModule(String controller, String icon, Boolean isDeleted, Boolean isShow, Integer level, String name, Integer orderNumber, AdminModule parentId, String routeLink) {
       this.controller = controller;
       this.icon = icon;
       this.isDeleted = isDeleted;
       this.isShow = isShow;
       this.level = level;
       this.name = name;
       this.orderNumber = orderNumber;
       this.parentId = parentId;
       this.routeLink = routeLink;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", nullable=false, insertable=false, updatable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Controller", length=150)
    public String getController() {
        return this.controller;
    }
    
    public void setController(String controller) {
        this.controller = controller;
    }

    
    @Column(name="Icon", length=50)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

    
    @Column(name="IsDeleted", insertable=false, updatable=false)
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    
    @Column(name="IsShow")
    public Boolean getIsShow() {
        return this.isShow;
    }
    
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    
    @Column(name="level")
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="OrderNumber")
    public Integer getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ParentID", updatable=false)
    public AdminModule getParentId() {
        return this.parentId;
    }
    
    public void setParentId(AdminModule parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="routeLink", length=150)
    public String getRouteLink() {
        return this.routeLink;
    }
    
    public void setRouteLink(String routeLink) {
        this.routeLink = routeLink;
    }




}


