package com.backend.entities;
// Generated Sep 24, 2019 11:35:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdminLogs generated by hbm2java
 */
@Entity
@Table(name="AdminLogs"
)
public class AdminLogs  implements java.io.Serializable {


     private int id;
     private Admin adminId;
     private Date createdDate;
     private String logContent;

    public AdminLogs() {
    }

    public AdminLogs(Admin adminId, Date createdDate, String logContent) {
       this.adminId = adminId;
       this.createdDate = createdDate;
       this.logContent = logContent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", nullable=false, insertable=false, updatable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AdminID")
    public Admin getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Admin adminId) {
        this.adminId = adminId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", insertable=false, updatable=false, length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LogContent")
    public String getLogContent() {
        return this.logContent;
    }
    
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }




}


