-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 14:45:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema doan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `doan` ;

-- -----------------------------------------------------
-- Table `doan`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doan`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `username` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `mailaddress` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doan`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doan`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doan`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doan`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `phone_number` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `total` BIGINT(20) NOT NULL,
  `date` DATE NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doan`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doan`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cate_id` INT(11) NOT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `price` BIGINT(20) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `views` INT(11) NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cate_id` (`cate_id` ASC) VISIBLE,
  CONSTRAINT `FKll9b6w9lwjkhiymqatom6jbd`
    FOREIGN KEY (`cate_id`)
    REFERENCES `doan`.`category` (`id`),
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`cate_id`)
    REFERENCES `doan`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `doan`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doan`.`order_detail` (
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `amount` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `FKb8bg2bkty0oksa3wiq5mp5qnc` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKb8bg2bkty0oksa3wiq5mp5qnc`
    FOREIGN KEY (`product_id`)
    REFERENCES `doan`.`product` (`id`),
  CONSTRAINT `FKplam7wxc4tjbgex0xyk8f0qxo`
    FOREIGN KEY (`order_id`)
    REFERENCES `doan`.`order` (`id`),
  CONSTRAINT `order_detail_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `doan`.`order` (`id`),
  CONSTRAINT `order_detail_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `doan`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
